auto: true

markdown: rdiscount
pygments: true
paginate: 10 
permalink: /:title

title: 不悔，就是不悔 
url: http://noregret.com
feed: /atom.xml
author_info: <a href="http://noregret.com/">No Regret</a>


analytics :
  provider : google
  google : 
      tracking_id : 'UA-63336513-1'
  getclicky :
    site_id :
